In [ ]:
import pandas as pd
import numpy as np

In [ ]:
brfss = pd.read_csv("./brfss.csv")
brfss.head()

In [ ]:
def replace_value(col, replace):
    print("="*10, col, "="*10)
    # before replacing
    print(brfss[col].value_counts())
    
    brfss[col].replace(replace, inplace=True)
    
    # after replacing
    print(brfss[col].value_counts())

In [ ]:
# type1: BLIND, DEAF, KIDNEY, LIVER1, LIVER2, HEARTDISEASE
# 1 -> 1
# 2 -> 0
# 7, 9 -> np.nan
type1 = {1: 1, 2: 0, 7: np.nan, 9: np.nan}

replace_value("BLIND", type1)
replace_value("DEAF", type1)
replace_value("KIDNEY", type1)
replace_value("LIVER1", type1)
replace_value("LIVER2", type1)
replace_value("HEARTDISEASE", type1)

========== BLIND ==========
2.0    399597
1.0     21745
7.0       952
9.0       655
Name: BLIND, dtype: int64
0.0    399597
1.0     21745
Name: BLIND, dtype: int64
========== DEAF ==========
2.0    384717
1.0     37578
7.0      1113
9.0       683
Name: DEAF, dtype: int64
0.0    384717
1.0     37578
Name: DEAF, dtype: int64
========== KIDNEY ==========
2.0    419779
1.0     17101
7.0      1488
9.0       322
Name: KIDNEY, dtype: int64
0.0    419779
1.0     17101
Name: KIDNEY, dtype: int64
========== LIVER1 ==========
2.0    10580
1.0      163
7.0       48
9.0       13
Name: LIVER1, dtype: int64
0.0    10580
1.0      163
Name: LIVER1, dtype: int64
========== LIVER2 ==========
2.0    10602
1.0       95
7.0       63
9.0       19
Name: LIVER2, dtype: int64
0.0    10602
1.0       95
Name: LIVER2, dtype: int64
========== HEARTDISEASE ==========
2.0    413207
1.0     22831
7.0      2319
9.0       334
Name: HEARTDISEASE, dtype: int64
0.0    413207
1.0     22831
Name: HEARTDISEASE, dtype: int64

In [ ]:
# type2: DIABETE, HYPERTENSION
# 1 -> 1
# 2, 3, 4 -> 0
# 7, 9 -> np.nan
type2 = {1: 1, 2: 0, 3: 0, 4: 0, 7: np.nan, 9: np.nan}

replace_value("DIABETE", type2)
replace_value("HYPERTENSION", type2)

========== DIABETE ==========
3.0    366342
1.0     57616
4.0      9942
2.0      3808
7.0       613
9.0       369
Name: DIABETE, dtype: int64
0.0    380092
1.0     57616
Name: DIABETE, dtype: int64
========== HYPERTENSION ==========
0.0    264648
1.0    172133
Name: HYPERTENSION, dtype: int64
0.0    264648
1.0    172133
Name: HYPERTENSION, dtype: int64

In [ ]:
brfss.tail()

,HEARTDISEASE,SEX,HEIGHT,WEIGHT,BLIND,DEAF,DIABETE,CHOLESTEROL,HYPERTENSION,KIDNEY,LIVER1,LIVER2,ALCOHOL,SMOKE
438688,0.0,2,502.0,135.0,0.0,0.0,2.0,2.0,1.0,0.0,NaN,NaN,204.0,1.0
438689,0.0,1,502.0,9999.0,1.0,0.0,1.0,2.0,1.0,0.0,NaN,NaN,888.0,2.0
438690,0.0,1,511.0,220.0,0.0,0.0,3.0,1.0,0.0,0.0,NaN,NaN,210.0,2.0
438691,0.0,1,600.0,175.0,0.0,0.0,3.0,2.0,1.0,0.0,NaN,NaN,203.0,2.0
438692,0.0,2,503.0,179.0,0.0,0.0,3.0,1.0,0.0,0.0,NaN,NaN,201.0,2.0